# Generated by Django 3.2.5 on 2022-08-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
