# Generated by Django 3.2.13 on 2022-08-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cube',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='freezer',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rack',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='shelf',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='_id',
            new_name='id',
        ),
    ]
