# Generated by Django 3.2.13 on 2022-08-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_patient_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
