# Generated by Django 3.2.5 on 2022-08-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sample__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date_of_archive',
            field=models.CharField(max_length=200),
        ),
    ]
