# Generated by Django 3.2.13 on 2022-08-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sample__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='0783872345', max_length=20),
        ),
    ]
