# Generated by Django 3.2.13 on 2022-08-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220825_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cube',
            name='freezer',
        ),
        migrations.RemoveField(
            model_name='cube',
            name='rack',
        ),
        migrations.RemoveField(
            model_name='cube',
            name='shelf',
        ),
    ]
