# Generated by Django 3.2.13 on 2022-08-25 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220825_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cube',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sample'),
        ),
    ]
