# Generated by Django 3.2.13 on 2022-08-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='narrative_name',
            field=models.CharField(default='sadf asd fadfg arsg dvadhf dgjhbn', max_length=500),
        ),
    ]
