# Generated by Django 3.2.5 on 2022-08-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_sample_date_of_archive'),
        ('home', '0006_patient_age'),
    ]

    operations = [
    ]
