# Generated by Django 3.2.13 on 2022-08-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_study_narrative_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('On going', 'On going'), ('Ended', 'Ended'), ('n/a', 'n/a')], default='On going', max_length=200),
        ),
    ]
