# Generated by Django 3.2.13 on 2022-08-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20220824_0901'),
        ('home', '0008_study_status'),
    ]

    operations = [
    ]
