# Generated by Django 3.2.13 on 2022-08-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220825_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
