# Generated by Django 3.2.13 on 2022-08-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_0007_merge_20220824_0901_0008_study_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='_id',
            new_name='id',
        ),
    ]
