# Generated by Django 3.2.13 on 2022-08-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220825_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
