# Generated by Django 3.2.13 on 2022-08-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220825_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample_aliquote',
            old_name='main_sample',
            new_name='sample',
        ),
    ]
