# Generated by Django 3.2.5 on 2022-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_main_sample_sample_aliquote_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='in_storage',
            field=models.BooleanField(default=False),
        ),
    ]
