# Generated by Django 3.2.13 on 2022-08-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_sample_in_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='in_storage',
            new_name='deleted',
        ),
    ]
