# Generated by Django 3.2.13 on 2022-08-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_in_storage_sample_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
    ]
