# Generated by Django 3.2.13 on 2022-08-31 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_sample_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='cube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myCube', to='home.cube'),
        ),
        migrations.AlterField(
            model_name='cube',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mySample', to='home.sample'),
        ),
    ]
